# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-15 06:10
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_art_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='picture',
            field=models.FileField(default=0, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
            preserve_default=False,
        ),
    ]
