# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-16 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20170715_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='art',
            name='picture',
            field=models.FileField(upload_to='media/'),
        ),
    ]
