# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-17 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0002_auto_20170717_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='body',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
