# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-17 17:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0003_auto_20170717_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='body',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='title',
        ),
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.EmailField(default=datetime.datetime(2017, 7, 17, 17, 30, 18, 171873, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
    ]
